pool:
  vmImage: ubuntu-latest

trigger: none

parameters:
- name: pat
  displayName: PAT token
  type: string

steps:
  - task: npmAuthenticate@0
    inputs:
      workingFile: .npmrc
  - task: UseDotNet@2
    displayName: Install .NET SDK
    inputs:
      packageType: sdk
      version: 7.x
  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: install -g renovate yarn
  - powershell: |
      renovate --token="${{ parameters.pat }}"
    displayName: Run Mend Renovate

