# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
  curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli
  chmod +x ./mendsastcli
  echo Mend SAST CLI downloaded successfully
  ./mendsastcli --name='ADO' --app '$(systemName)'
  
env:
SAST_ORGANIZATION: $(sast.organisation)
SASTCLI_TOKEN: $(sast.clitoken)
SAST_SERVER: $(sast.server)
