

---
trigger:
  - main
pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
      curl -LJO https://downloads-sast.mend.io/sast-cli/linux/mendsastcli
      chmod +x ./mendsastcli
      echo Mend SAST CLI downloaded successfully
      ./mendsastcli --name='test1234' --app 'test1234'
  env:
    SASTCLI_TOKEN: $(sast.clitoken)
    SAST_SERVER: $(sast.server)
